[package]
name = "engine"
version = "0.1.0"
authors = ["Tin Rabzelj <tin.rabzelj@gmail.com>"]
edition = "2018"

[dependencies]
graph = { path = "../graph" }
serde = "1.0.103"
serde_derive = "1.0.103"
config = "0.9.3"
crossbeam = "0.7.3"
